name: Base Docker

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/docker_reusable.yaml'
      - '.github/workflows/docker_base.yaml'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  docker_base:
    uses: ./.github/workflows/docker_reusable.yaml
    with:
      registry: quay.io
      image_name: broadinstitute/macosko-pipelines_base
      dockerfile: Dockerfile
    secrets: inherit
    permissions:
      contents: read
